#Spring
server:
  port: 8181
spring:
  main:
    banner-mode: off

#Logging
logging:
  level:
    root: info
    cz:
      test:
        routing: trace

#data url
countries:
  url: https://raw.githubusercontent.com

#Swagger - Open API
springdoc:
  swagger-ui:
    path: /
  api-docs:
    path: /api-docs
  writer-with-default-pretty-printer: true